
Fatal error: %s
Stack trace:
#0 %s(%d): test(Object(ClassName))
#1 {main}
  thrown in %s on line %d